### ISSUE TITLE
ComfyUI里面无法载入(it can't be load in comfyUI)

### ISSUE THREAD

**Issue by yli6hz** [alimama-creative/FLUX-Controlnet-Inpainting#16]
错误提示如下：Error show as below:

Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\FLUX-Controlnet-Inpainting\__init__.py", line 3, in <module>
    from controlnet_flux import FluxControlNetModel
ModuleNotFoundError: No module named 'controlnet_flux'

Cannot import D:\ComfyUI\ComfyUI\custom_nodes\FLUX-Controlnet-Inpainting module for custom nodes: No module named 'controlnet_flux'

我看文件里本身就没有init.py的，但不知为何导入时会提示需要这个文件。请帮忙，谢谢！I find there is no "init.py" in folder but the system requires to load this file, I don't why. Please give a help. thanks!

**Comment by lvpeiyia** [comment]
我也遇到一样的问题

**Comment by JPlin** [comment]
该Github仓库是Diffusers框架推理用的，Comfyui推理不用本github代码，直接导入workflow就可以了

**Comment by zzddwyff** [comment]
那FLUX-Controlnet-Inpainting应该放在哪里，我放进custom_node里之后导入工作流依旧显示节点缺失

**Comment by Anluo28** [comment]
遇到一样的问题

**Comment by araleza** [comment]
If you have all the nodes working except for ControlNetInpaintingAlimamaApply, then your ComfyUI installation is likely out of date. This node seems to be part of ComfyUI itself now.

如果 ControlNetInpaintingAlimamaApply 之外的所有節點都正常運作，則您的 ComfyUI 安裝可能已過時。該節點現在似乎是 ComfyUI 本身的一部分。

**Comment by zyj802** [comment]
> 如果除 ControlNetInpaintingAlimamaApply 之外的所有节点均正常工作，则您的 ComfyUI 安装可能已过期。此节点现在似乎是 ComfyUI 本身的一部分。
> 
> 如果 ControlNetInpaintingAlimamaApply 之外的所有节点都正常运行，则您的 ComfyUI 安装可能已经过时。该节点现在似乎是 ComfyUI 本身的一部分。

感谢你的答复，更新comfyui本体后成功加载，这个问题原本一直在困扰我
