### ISSUE TITLE
RuntimeError: The size of tensor a (128) must match the size of tensor b (2) at non-singleton dimension 6

### ISSUE THREAD

**Issue by everythoughthelps** [alimama-creative/FLUX-Controlnet-Inpainting#21]
Got the size matching error:
Traceback (most recent call last):
  File "/data4/panmeng/flux_ctrl_inpainting/main.py", line 38, in <module>
    result = pipe(
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data4/panmeng/flux_ctrl_inpainting/pipeline_flux_controlnet_inpaint.py", line 959, in __call__
    ) = self.controlnet(
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data4/panmeng/flux_ctrl_inpainting/controlnet_flux.py", line 329, in forward
    encoder_hidden_states, hidden_states = block(
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data4/panmeng/flux_ctrl_inpainting/transformer_flux.py", line 213, in forward
    attn_output, context_attn_output = self.attn(
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 490, in forward
    return self.processor(
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/diffusers/models/attention_processor.py", line 1762, in __call__
    query = apply_rotary_emb(query, image_rotary_emb)
  File "/home/panmeng/miniconda3/envs/flux_inpainting/lib/python3.9/site-packages/diffusers/models/embeddings.py", line 680, in apply_rotary_emb
    out = (x.float() * cos + x_rotated.float() * sin).to(x.dtype)
RuntimeError: The size of tensor a (128) must match the size of tensor b (2) at non-singleton dimension 6,
any one soloved?

**Comment by 1058441072** [comment]
+1

**Comment by JPlin** [comment]
#7
